sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew docker


after_success:
  - docker login  -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag  lumue/filescanner-server:master-SNAPSHOT lumue/filescanner-server:latest
  - docker push lumue/filescanner-server:master-SNAPSHOT
  - docker push lumue/filescanner-server:latest

