filescanner_server:34xc  :
    - filescanner_elasticsearch

filescanner_elasticsearch:
  image: elasticsearch:1.5.2
  log_driver: "syslog"
  log_opt:
    syslog-tag: "filescanner_elasticsearch"
    syslog-address: "udp://192.168.1.105:514"
  volumes:
    - /data/docker-volumes/filescanner/elasticsearch/config:/usr/share/elasticsearch/config
    - /data/docker-volumes/filescanner/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9201:9200"
    - "9301:9300"

filescanner_client:
  image: media:5000/filescanner-webclient
  log_driver: "syslog"
  log_opt:
    syslog-tag: "filescanner_client"
    syslog-address: "udp://192.168.1.105:514"
  ports:
    - "8004:80"
  links:
    - filescanner_server
